### ISSUE TITLE
Trails@1.0.0 compatibility

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-hapi#106]
This trailpack is not compatible with the last Trails version v1.0. Dependencies need to be updated in order to be compatible (trailpack-webserver)

**Comment by tjwebb** [comment]
I think this is resolved in trailpack-hapi 1.0.0.

**Comment by jaumard** [comment]
@tjwebb Don't think so as it use `trailpack-webserver` alpha version... https://github.com/trailsjs/trailpack-hapi/blob/master/package.json#L35 it should use `^1.0.1`
`trailpack` dependency can be removed by the same time :)

**Comment by konstantinzolotarev** [comment]
@jaumard @tjwebb please check #115
