### ISSUE TITLE
lodash update missing methods

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-hapi#28]
With lodash 4.0.0 a lot of methods disappeared like `contains` -> `includes`, `pluck` -> `map`, can't make a PR cause they're other error when I do this and maybe @tjwebb have more recent version in local.

**Comment by jaumard** [comment]
also `unique` -> `uniq`

**Comment by tjwebb** [comment]
Yea, this is why I hate npm3. If I upgrade a dependency in one module, I have to update it everywhere. I'm working on this today.

**Comment by jaumard** [comment]
Hum normally you don't have to, if multiple modules use different version of a module npm3 works like npm2 (normally :smile:) but yeah sometimes npm3 do weird things :( as I see you fix this on last version so I'm closing this thanks.
