### ISSUE TITLE
Deprecated lodash function aliases

### ISSUE THREAD

**Issue by jakobrosenberg** [trailsjs/trailpack-hapi#31]
`server.js` and `index.js` use the following functions aliases which have been deprecated. The new aliases are shown after the arrows.

`_.contain` => `_.includes` 
`_.pluck` => `_.map`
`_.unique` => `_.uniq`

**Comment by jaumard** [comment]
Already fix on the master. Related to https://github.com/trailsjs/trailpack-hapi/issues/28 feel free to reopen if it's not the case
