### ISSUE TITLE
New NPM version needed

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-hapi#76]
@tjwebb is the master stable enough for a new npm version ? Because I was thinking the `config/web.js` archetype was deploy but Trails without `config/web.js` was so the app crash on fresh generation from generator.

**Comment by weyj4** [comment]
We need to put a recent version on npm anyway to serve assets without symlinking. I have one more PR maybe we should merge before publishing, [https://github.com/trailsjs/trailpack-hapi/pull/77](https://github.com/trailsjs/trailpack-hapi/pull/77)

**Comment by jaumard** [comment]
Will fix https://github.com/trailsjs/trails/issues/149

**Comment by jaumard** [comment]
Fixed
