### ISSUE TITLE
View engine

### ISSUE THREAD

**Issue by weyj4** [trailsjs/trailpack-hapi#84]
Should the view engine be configured in config.web.views or config.views? Right now it seems to work in either.

**Comment by jaumard** [comment]
Yeah for now it's work in both (same for express). In fact in `config.views` it's only a unify way to define a template engine and under `config.web.views` it's a web server specific way who allow to use multiple template engine. But yeah not sure both are needed...

**Comment by jaumard** [comment]
It can be confusing for users because if views are configured under `web.js` the template engine will not be visible under `Basic info` logs when Trails start...
